query GetLiquidityGauges {
  getLiquidityGauges {
    id
  }
}

query UserGetUserStakesQuery($user: String!, $poolIds: [String!]!) {
  getUserGaugeStakes(user: $user, poolIds: $poolIds) {
    id
  }
}
