query GetLiquidityGauges {
  getLiquidityGauges {
    id
    address
    symbol
    poolId
    totalSupply
    depositFee
    withdrawFee
    isKilled

    factory {
      id
    }

    rewardTokens {
      tokenAddress
      decimals
      symbol
      logoURI
    }

    pool {
      id
      name
      address
      poolType
      tokensList
      tokens {
        address
        weight
        logoURI
        symbol
      }
    }

    currentEpochBribes {
      ...GaugeBribeFragment
    }

    nextEpochBribes {
      ...GaugeBribeFragment
    }
  }
}

query GetUserStakes($user: String!, $poolIds: [String!]!) {
  getUserGaugeStakes(user: $user, poolIds: $poolIds) {
    id
  }
}

query GetUserVeLockInfo {
  userGetVeLockInfo {
    lockedAmount
    lockEndDate
    totalSupply
    currentBalance
    epoch
    hasExistingLock
    isExpired
    percentOwned
  }
}

fragment GaugeBribeFragment on GaugeBribe {
  briber
  gauge
  amount
  epochStartTime
  valueUSD
  epochWeekLabel
  token {
    address
    symbol
    logoURI
  }
}
