query GetLiquidityGauges {
  getLiquidityGauges {
    id
    address
    symbol
    poolId
    totalSupply
    depositFee
    withdrawFee
    isKilled

    factory {
      id
    }

    rewardTokens {
      id
      decimals
      symbol
    }

    pool {
      id
      name
      address
      poolType
      tokensList
      tokens {
        address
        weight
        logoURI
        symbol
      }
    }
  }
}

query GetUserStakes($user: String!, $poolIds: [String!]!) {
  getUserGaugeStakes(user: $user, poolIds: $poolIds) {
    id
  }
}

query GetUserVeLockInfo {
  userGetVeLockInfo {
    lockedAmount
    lockEndDate
    totalSupply
    currentBalance
    epoch
    hasExistingLock
    isExpired
    percentOwned
  }
}
