query GetUserData {
  balances: userGetPoolBalances {
    poolId
    tokenAddress
    tokenPrice
    totalBalance
    stakedBalance
    walletBalance
  }
  staking: userGetStaking {
    id
    type
    address
    gauge {
      id
      gaugeAddress
      depositFee
      withdrawFee
      rewards {
        id
        rewardPerSecond
        tokenAddress
      }
    }
  }

  boosts: userGetGaugeBoosts {
    poolId
    gaugeAddress
    boost
  }
}

mutation UserSyncBalance($poolId: String!) {
  userSyncBalance(poolId: $poolId)
}
