query GetUserData {
  balances: userGetPoolBalances {
    poolId
    tokenAddress
    tokenPrice
    totalBalance
    stakedBalance
    walletBalance
  }
  staking: userGetStaking {
    id
    type
    address
    gauge {
      id
      gaugeAddress
      depositFee
      withdrawFee
      rewards {
        id
        rewardPerSecond
        tokenAddress
      }
    }
  }

  boosts: userGetGaugeBoosts {
    poolId
    gaugeAddress
    boost
  }
}

query GetUserProtocolRewards {
  protocolRewards: userGetProtocolRewardInfo {
    poolId
    token
    tokenInfo {
      logoURI
      valueUSD
    }
    amount
    isBPT
    tokenList {
      address
      logoURI
    }
  }
}

mutation UserSyncBalance($poolId: String!) {
  userSyncBalance(poolId: $poolId)
}
