query GetRewardPools($user: String) {
  getRewardPools(user: $user) {
    address
    startBlock
    endBlock
    blocksRemaining
    daysRemaining
    amountStaked
    amountStakedValue
    isPartnerPool
    rewardToken {
      address
      name
      symbol
      rewardPerBlock
      logoURI
    }

    aprs {
      apr
      daily
    }

    userInfo {
      poolAddress
      amountDeposited
      amountDepositedFull
      depositValue
      hasPendingRewards
      pendingRewards
      pendingRewardValue
      percentageOwned
    }
  }
}
