query GetRewardPools {
  getRewardPools {
    address
    startBlock
    endBlock
    blocksRemaining
    rewardToken {
      logoURI
    }
    aprs {
      apr
      daily
    }
  }
}
