query GetRewardPools {
  getRewardPools {
    address
    startBlock
    endBlock
    blocksRemaining
    amountStaked
    amountStakedValue
    isPartnerPool
    rewardToken {
      address
      name
      symbol
      rewardPerBlock
      logoURI
    }
    aprs {
      apr
      daily
    }
  }
}
