import { RewardPool } from '~/apollo/generated/graphql-codegen-generated';

export const COMING_POOLS: any[] = [
  {
    address: '',
    amountStaked: '0',
    amountStakedValue: '0.00',
    startBlock: 0,
    endBlock: 0,
    blocksRemaining: '0',
    daysRemaining: '0',
    isPartnerPool: false,
    rewardToken: {
      address: '0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c',
      name: 'Wrapped BNB',
      symbol: 'WBNB',
      logoURI: 'https://assets.coingecko.com/coins/images/825/small/bnb-icon2_2x.png?1644979850',
      rewardPerBlock: '0',
      price: null,
    },
    userInfo: null,
    aprs: {
      daily: '0',
      apr: '0',
    },
  },
  {
    address: '',
    amountStaked: '0',
    amountStakedValue: '0.00',
    startBlock: 0,
    endBlock: 0,
    blocksRemaining: '0',
    daysRemaining: '0',
    isPartnerPool: false,
    rewardToken: {
      address: '0x2170Ed0880ac9A755fd29B2688956BD959F933F8',
      name: 'Wrapped Ether',
      symbol: 'WETH',
      logoURI: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png?1595348880',
      rewardPerBlock: '0',
      price: null,
    },
    userInfo: null,
    aprs: {
      daily: '0',
      apr: '0',
    },
  },
  {
    address: '',
    amountStaked: '0',
    amountStakedValue: '0.00',
    startBlock: 0,
    endBlock: 0,
    blocksRemaining: '0',
    daysRemaining: '0',
    isPartnerPool: false,
    rewardToken: {
      address: '0xFa4b16b0f63F5A6D0651592620D585D308F749A4',
      name: 'Ashare',
      symbol: 'ASHARE',
      logoURI: 'https://assets.coingecko.com/coins/images/23974/small/ashare.png?1645871503',
      rewardPerBlock: '0',
      price: null,
    },
    userInfo: null,
    aprs: {
      daily: '0',
      apr: '0',
    },
  },
  {
    address: '',
    amountStaked: '0',
    amountStakedValue: '0.00',
    startBlock: 0,
    endBlock: 0,
    blocksRemaining: '0',
    daysRemaining: '0',
    isPartnerPool: false,
    rewardToken: {
      address: '0x6640e6f8e3DD1Fb5D7361ee2249E1ea23cB2C297',
      name: 'Serene',
      symbol: 'SERENE V2',
      logoURI:
        'https://github.com/0xBriz/token-list/blob/3e2a65b205c0185ad59fae2c9b46627f060e3cad/images/serene.png?raw=true',
      rewardPerBlock: '0',
      price: null,
    },
    userInfo: null,
    aprs: {
      daily: '0',
      apr: '0',
    },
  },
  {
    address: '',
    amountStaked: '0',
    amountStakedValue: '0.00',
    startBlock: 0,
    endBlock: 0,
    blocksRemaining: '0',
    daysRemaining: '0',
    isPartnerPool: false,
    rewardToken: {
      address: '0xb9E05B4C168B56F73940980aE6EF366354357009',
      name: 'Amethyst',
      symbol: 'AMES',
      logoURI: 'https://assets.coingecko.com/coins/images/23973/small/ames.png?1645871205',
      rewardPerBlock: '0',
      price: null,
    },
    userInfo: null,
    aprs: {
      daily: '0',
      apr: '0',
    },
  },
];
