query GetPoolsForGauges($gaugeIds: [String!]!) {
  getPoolsForGauges(gaugeIds: $gaugeIds) {
    id
    address
    poolType
    tokensList
    tokens {
      address
      weight
    }
  }
}
